version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_study_app
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_UPLOAD_MB=${MAX_UPLOAD_MB:-200}
      - FLASK_ENV=${FLASK_ENV:-production}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DATABASE_URL=sqlite:////app/data/ai_study.db
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - whisper_cache:/home/appuser/.cache/whisper
      - huggingface_cache:/home/appuser/.cache/huggingface
    restart: unless-stopped
    networks:
      - ai_study_network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  # Nginx для production (опционально)
  nginx:
    image: nginx:alpine
    container_name: ai_study_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - static_volume:/app/static:ro
    depends_on:
      - app
    networks:
      - ai_study_network
    profiles:
      - production

  # Redis для кэширования (опционально)
  redis:
    image: redis:alpine
    container_name: ai_study_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - ai_study_network
    profiles:
      - with-cache

volumes:
  whisper_cache:
    driver: local
  huggingface_cache:
    driver: local
  redis_data:
    driver: local
  static_volume:
    driver: local

networks:
  ai_study_network:
    driver: bridge